version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/jysa-radio:rw,cached
    environment:
      - APP_ENV=dev
    platform: linux/amd64

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/jysa-radio:ro,cached
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    platform: linux/amd64

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"
    platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - database
    platform: linux/amd64

  database:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - database_data:/var/lib/mysql
    platform: linux/amd64

volumes:
  database_data: