services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/jysa-radio:cached
    environment:
      - APP_ENV=dev

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - .:/var/www/jysa-radio:cached
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
