# Use the base Nginx image
FROM nginx:alpine

# Copy the main nginx.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf

# Copy the default server configuration
COPY docker/default.conf /etc/nginx/conf.d/default.conf

# Copy your application files
COPY . /var/www/jysa-radio

# Create cache directory and set permissions
RUN mkdir -p /var/cache/nginx && chown -R nginx:nginx /var/cache/nginx

# Change the owner of the application files to the nginx user
RUN chown -R nginx:nginx /var/www/jysa-radio

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
